version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package.json" }}
      - run: npm i
      - save_cache:
          key: node_modules-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: ~/project # ~/project is the default working_directory, i.e. steps are run in this directory unless otherwise specified
          paths: .

  test:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm test

  build_client_version:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Build client version
          command: npm run client-build
      - persist_to_workspace:
          root: ~/client-build
          paths: ./dist

  test_client_version:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: ~/client-build
      - run: cd ~/client-build && npm test

  publish_to_npm:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Authorize NPM
          command: echo "//registry.npmjs.org/:_authToken=$PRIVATE_NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish to NPM
          command: npm publish

  publish_client_version_to_npm:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: ~/client-build
      - run:
          name: Authorize NPM
          command: echo "//registry.npmjs.org/:_authToken=$PRIVATE_NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish to NPM
          command: cd ~/client-build && npm publish

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/

      - build_client_version:
          requires:
            - build
          filters:
            tags:
              only: /.*/

      - test_client_version:
          requires:
            - build_client_version
          filters:
            tags:
              only: /.*/

      - publish_to_npm:
          context: org-global
          requires:
            - test
            - test_client_version
          filters:
            tags:
              only: /^v[0-9]+.*/
            branches:
              ignore: /.*/
    
      - publish_client_version_to_npm:
          context: org-global
          requires:
            - publish_to_npm
          filters:
            tags:
              only: /^v[0-9]+.*/
            branches:
              ignore: /.*/
